version: '3'
services:
  cronicle:
    build: .
    ports:
      - "3012:3012"  # Ajusta el puerto si es necesario
    volumes:
      - cronicle_data:/opt/cronicle/data
      - cronicle_logs:/opt/cronicle/logs
      - cronicle_plugins:/opt/cronicle/plugins
      - cronicle_backup:/opt/cronicle/backup
    restart: always

volumes:
  cronicle_data:
  cronicle_logs:
  cronicle_plugins:
  cronicle_backup:
