name: terraform-plan

on:
  pull_request:
    paths:
      - "terraform/**"

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -recursive -check
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -no-color -out=tfplan
