apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-http-from-ingress
  namespace: my-app
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: my-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
