FROM lscr.io/linuxserver/doublecommander:latest

# set version label
ARG DEBIAN_FRONTEND="noninteractive"


RUN \
  echo "**** install packages ****" && \
  apt-get update && \
  apt-get install -y \
    gnome-terminal \
    kate 
# install 
RUN 





# ports and volumes
EXPOSE 3000


COPY /root /



