apiVersion: v1
kind: Service
metadata:
  labels:
    service: workbench
  name: workbench
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: workbench
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: workbench
  name: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      service: workbench
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: workbench
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Argentina/Buenos_Aires
          image: lscr.io/linuxserver/mysql-workbench:latest
          name: workbench
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /config
              name: workbench-config
            - mountPath: /data
              name: workbench-data
          # solo seleccionar nodo beta.kubernetes.io/arch=amd64
          nodeSelector:
            beta.kubernetes.io/arch: amd64
      restartPolicy: Always
      volumes:
        - name: workbench-config
          persistentVolumeClaim:
            claimName: workbench-config
        - name: workbench-data
          persistentVolumeClaim:
            claimName: workbench-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: workbench-config
  name: workbench-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # Especifica la clase de almacenamiento gp2 aquí
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: workbench-data
  name: workbench-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # Especifica la clase de almacenamiento gp2 aquí
  resources:
    requests:
      storage: 3Gi
